**Data Acquisition**

In [1]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

In [2]:
#importing the dataset from kaggle
!kaggle datasets download -d tmdb/tmdb-movie-metadata

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /root/.kaggle/kaggle.json'
Downloading tmdb-movie-metadata.zip to /content
 56% 5.00M/8.89M [00:00<00:00, 39.3MB/s]
100% 8.89M/8.89M [00:00<00:00, 55.9MB/s]

In [3]:
#unzip the dataset
import zipfile
zip_ref = zipfile.ZipFile('/content/tmdb-movie-metadata.zip','r')
zip_ref.extractall('/content')
zip_ref.close()

In [4]:
#Importing the libraries
import numpy as np
import pandas as pd
import ast

In [5]:
movies = pd.read_csv('/content/tmdb_5000_movies.csv')
credits = pd.read_csv('/content/tmdb_5000_credits.csv')

**Data Pre-Processing**

In [6]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [7]:
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [ ]:
credits.head(1)['cast'].values

In [9]:
#merging the dataset to one
movies = movies.merge(credits,on='title')

In [10]:
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bondâ€™s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [11]:
credits.shape

(4803, 4)

In [12]:
# we will keep only required features in our dataset rest will be neglected
movies = movies[['movie_id','title','overview','genres','keywords','cast','crew']]

In [13]:
#checking for null values
movies.head()
movies.isnull().sum()

movie_id    0
title       0
overview    3
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [14]:
movies.dropna(inplace=True)

In [15]:
#Looking for duplicated row
movies.duplicated().sum()

0

In [16]:
#Now based upon overview, genre, keyword, cast & crew we will create taglines

movies['genres'][0]

'[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]'

In [17]:
#We want only values of the key (name)
def convert(list):
  l=[]
  for i in ast.literal_eval(list):       #for converting string of list to list only
    value = i['name']
    l.append(value)
  return l
movies['genres'] = movies['genres'].apply(convert)

In [18]:
#for converting string of list to list
import ast
ast.literal_eval('[{"id": 28, "name": "Action"}, {"id": 12, "name": "Adventure"}, {"id": 14, "name": "Fantasy"}, {"id": 878, "name": "Science Fiction"}]')

[{'id': 28, 'name': 'Action'},
 {'id': 12, 'name': 'Adventure'},
 {'id': 14, 'name': 'Fantasy'},
 {'id': 878, 'name': 'Science Fiction'}]

In [19]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [20]:
# We will apply same function to keywords feature also
movies['keywords'] = movies['keywords'].apply(convert)

In [21]:
movies['keywords'][0]

['culture clash',
 'future',
 'space war',
 'space colony',
 'society',
 'space travel',
 'futuristic',
 'romance',
 'space',
 'alien',
 'tribe',
 'alien planet',
 'cgi',
 'marine',
 'soldier',
 'battle',
 'love affair',
 'anti war',
 'power relations',
 'mind and soul',
 '3d']

In [22]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [23]:
#Now we will take only first 3 actors name from the cast
def convert2(obj):
  j=0
  list=[]
  for i in ast.literal_eval(obj):
    if j<3:
      list.append(i['name'])
      j+=1
  return list

In [24]:
movies['cast'] = movies['cast'].apply(convert2)

In [25]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [26]:
   movies['crew'][0]

'[{"credit_id": "52fe48009251416c750aca23", "department": "Editing", "gender": 0, "id": 1721, "job": "Editor", "name": "Stephen E. Rivkin"}, {"credit_id": "539c47ecc3a36810e3001f87", "department": "Art", "gender": 2, "id": 496, "job": "Production Design", "name": "Rick Carter"}, {"credit_id": "54491c89c3a3680fb4001cf7", "department": "Sound", "gender": 0, "id": 900, "job": "Sound Designer", "name": "Christopher Boyes"}, {"credit_id": "54491cb70e0a267480001bd0", "department": "Sound", "gender": 0, "id": 900, "job": "Supervising Sound Editor", "name": "Christopher Boyes"}, {"credit_id": "539c4a4cc3a36810c9002101", "department": "Production", "gender": 1, "id": 1262, "job": "Casting", "name": "Mali Finn"}, {"credit_id": "5544ee3b925141499f0008fc", "department": "Sound", "gender": 2, "id": 1729, "job": "Original Music Composer", "name": "James Horner"}, {"credit_id": "52fe48009251416c750ac9c3", "department": "Directing", "gender": 2, "id": 2710, "job": "Director", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750ac9d9", "department": "Writing", "gender": 2, "id": 2710, "job": "Writer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca17", "department": "Editing", "gender": 2, "id": 2710, "job": "Editor", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca29", "department": "Production", "gender": 2, "id": 2710, "job": "Producer", "name": "James Cameron"}, {"credit_id": "52fe48009251416c750aca3f", "department": "Writing", "gender": 2, "id": 2710, "job": "Screenplay", "name": "James Cameron"}, {"credit_id": "539c4987c3a36810ba0021a4", "department": "Art", "gender": 2, "id": 7236, "job": "Art Direction", "name": "Andrew Menzies"}, {"credit_id": "549598c3c3a3686ae9004383", "department": "Visual Effects", "gender": 0, "id": 6690, "job": "Visual Effects Producer", "name": "Jill Brooks"}, {"credit_id": "52fe48009251416c750aca4b", "department": "Production", "gender": 1, "id": 6347, "job": "Casting", "name": "Margery Simkin"}, {"credit_id": "570b6f419251417da70032fe", "department": "Art", "gender": 2, "id": 6878, "job": "Supervising Art Director", "name": "Kevin Ishioka"}, {"credit_id": "5495a0fac3a3686ae9004468", "department": "Sound", "gender": 0, "id": 6883, "job": "Music Editor", "name": "Dick Bernstein"}, {"credit_id": "54959706c3a3686af3003e81", "department": "Sound", "gender": 0, "id": 8159, "job": "Sound Effects Editor", "name": "Shannon Mills"}, {"credit_id": "54491d58c3a3680fb1001ccb", "department": "Sound", "gender": 0, "id": 8160, "job": "Foley", "name": "Dennie Thorpe"}, {"credit_id": "54491d6cc3a3680fa5001b2c", "department": "Sound", "gender": 0, "id": 8163, "job": "Foley", "name": "Jana Vance"}, {"credit_id": "52fe48009251416c750aca57", "department": "Costume & Make-Up", "gender": 1, "id": 8527, "job": "Costume Design", "name": "Deborah Lynn Scott"}, {"credit_id": "52fe48009251416c750aca2f", "department": "Production", "gender": 2, "id": 8529, "job": "Producer", "name": "Jon Landau"}, {"credit_id": "539c4937c3a36810ba002194", "department": "Art", "gender": 0, "id": 9618, "job": "Art Direction", "name": "Sean Haworth"}, {"credit_id": "539c49b6c3a36810c10020e6", "department": "Art", "gender": 1, "id": 12653, "job": "Set Decoration", "name": "Kim Sinclair"}, {"credit_id": "570b6f2f9251413a0e00020d", "department": "Art", "gender": 1, "id": 12653, "job": "Supervising Art Director", "name": "Kim Sinclair"}, {"credit_id": "54491a6c0e0a26748c001b19", "department": "Art", "gender": 2, "id": 14350, "job": "Set Designer", "name": "Richard F. Mays"}, {"credit_id": "56928cf4c3a3684cff0025c4", "department": "Production", "gender": 1, "id": 20294, "job": "Executive Producer", "name": "Laeta Kalogridis"}, {"credit_id": "52fe48009251416c750aca51", "department": "Costume & Make-Up", "gender": 0, "id": 17675, "job": "Costume Design", "name": "Mayes C. Rubeo"}, {"credit_id": "52fe48009251416c750aca11", "department": "Camera", "gender": 2, "id": 18265, "job": "Director of Photography", "name": "Mauro Fiore"}, {"credit_id": "5449194d0e0a26748f001b39", "department": "Art", "gender": 0, "id": 42281, "job": "Set Designer", "name": "Scott Herbertson"}, {"credit_id": "52fe48009251416c750aca05", "department": "Crew", "gender": 0, "id": 42288, "job": "Stunts", "name": "Woody Schultz"}, {"credit_id": "5592aefb92514152de0010f5", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Makeup Artist", "name": "Linda DeVetta"}, {"credit_id": "5592afa492514152de00112c", "department": "Costume & Make-Up", "gender": 0, "id": 29067, "job": "Hairstylist", "name": "Linda DeVetta"}, {"credit_id": "54959ed592514130fc002e5d", "department": "Camera", "gender": 2, "id": 33302, "job": "Camera Operator", "name": "Richard Bluck"}, {"credit_id": "539c4891c3a36810ba002147", "department": "Art", "gender": 2, "id": 33303, "job": "Art Direction", "name": "Simon Bright"}, {"credit_id": "54959c069251417a81001f3a", "department": "Visual Effects", "gender": 0, "id": 113145, "job": "Visual Effects Supervisor", "name": "Richard Martin"}, {"credit_id": "54959a0dc3a3680ff5002c8d", "department": "Crew", "gender": 2, "id": 58188, "job": "Visual Effects Editor", "name": "Steve R. Moore"}, {"credit_id": "52fe48009251416c750aca1d", "department": "Editing", "gender": 2, "id": 58871, "job": "Editor", "name": "John Refoua"}, {"credit_id": "54491a4dc3a3680fc30018ca", "department": "Art", "gender": 0, "id": 92359, "job": "Set Designer", "name": "Karl J. Martin"}, {"credit_id": "52fe48009251416c750aca35", "department": "Camera", "gender": 1, "id": 72201, "job": "Director of Photography", "name": "Chiling Lin"}, {"credit_id": "52fe48009251416c750ac9ff", "department": "Crew", "gender": 0, "id": 89714, "job": "Stunts", "name": "Ilram Choi"}, {"credit_id": "54959c529251416e2b004394", "department": "Visual Effects", "gender": 2, "id": 93214, "job": "Visual Effects Supervisor", "name": "Steven Quale"}, {"credit_id": "54491edf0e0a267489001c37", "department": "Crew", "gender": 1, "id": 122607, "job": "Dialect Coach", "name": "Carla Meyer"}, {"credit_id": "539c485bc3a368653d001a3a", "department": "Art", "gender": 2, "id": 132585, "job": "Art Direction", "name": "Nick Bassett"}, {"credit_id": "539c4903c3a368653d001a74", "department": "Art", "gender": 0, "id": 132596, "job": "Art Direction", "name": "Jill Cormack"}, {"credit_id": "539c4967c3a368653d001a94", "department": "Art", "gender": 0, "id": 132604, "job": "Art Direction", "name": "Andy McLaren"}, {"credit_id": "52fe48009251416c750aca45", "department": "Crew", "gender": 0, "id": 236696, "job": "Motion Capture Artist", "name": "Terry Notary"}, {"credit_id": "54959e02c3a3680fc60027d2", "department": "Crew", "gender": 2, "id": 956198, "job": "Stunt Coordinator", "name": "Garrett Warren"}, {"credit_id": "54959ca3c3a3686ae300438c", "department": "Visual Effects", "gender": 2, "id": 957874, "job": "Visual Effects Supervisor", "name": "Jonathan Rothbart"}, {"credit_id": "570b6f519251412c74001b2f", "department": "Art", "gender": 0, "id": 957889, "job": "Supervising Art Director", "name": "Stefan Dechant"}, {"credit_id": "570b6f62c3a3680b77007460", "department": "Art", "gender": 2, "id": 959555, "job": "Supervising Art Director", "name": "Todd Cherniawsky"}, {"credit_id": "539c4a3ac3a36810da0021cc", "department": "Production", "gender": 0, "id": 1016177, "job": "Casting", "name": "Miranda Rivers"}, {"credit_id": "539c482cc3a36810c1002062", "department": "Art", "gender": 0, "id": 1032536, "job": "Production Design", "name": "Robert Stromberg"}, {"credit_id": "539c4b65c3a36810c9002125", "department": "Costume & Make-Up", "gender": 2, "id": 1071680, "job": "Costume Design", "name": "John Harding"}, {"credit_id": "54959e6692514130fc002e4e", "department": "Camera", "gender": 0, "id": 1177364, "job": "Steadicam Operator", "name": "Roberto De Angelis"}, {"credit_id": "539c49f1c3a368653d001aac", "department": "Costume & Make-Up", "gender": 2, "id": 1202850, "job": "Makeup Department Head", "name": "Mike Smithson"}, {"credit_id": "5495999ec3a3686ae100460c", "department": "Visual Effects", "gender": 0, "id": 1204668, "job": "Visual Effects Producer", "name": "Alain Lalanne"}, {"credit_id": "54959cdfc3a3681153002729", "department": "Visual Effects", "gender": 0, "id": 1206410, "job": "Visual Effects Supervisor", "name": "Lucas Salton"}, {"credit_id": "549596239251417a81001eae", "department": "Crew", "gender": 0, "id": 1234266, "job": "Post Production Supervisor", "name": "Janace Tashjian"}, {"credit_id": "54959c859251416e1e003efe", "department": "Visual Effects", "gender": 0, "id": 1271932, "job": "Visual Effects Supervisor", "name": "Stephen Rosenbaum"}, {"credit_id": "5592af28c3a368775a00105f", "department": "Costume & Make-Up", "gender": 0, "id": 1310064, "job": "Makeup Artist", "name": "Frankie Karena"}, {"credit_id": "539c4adfc3a36810e300203b", "department": "Costume & Make-Up", "gender": 1, "id": 1319844, "job": "Costume Supervisor", "name": "Lisa Lovaas"}, {"credit_id": "54959b579251416e2b004371", "department": "Visual Effects", "gender": 0, "id": 1327028, "job": "Visual Effects Supervisor", "name": "Jonathan Fawkner"}, {"credit_id": "539c48a7c3a36810b5001fa7", "department": "Art", "gender": 0, "id": 1330561, "job": "Art Direction", "name": "Robert Bavin"}, {"credit_id": "539c4a71c3a36810da0021e0", "department": "Costume & Make-Up", "gender": 0, "id": 1330567, "job": "Costume Supervisor", "name": "Anthony Almaraz"}, {"credit_id": "539c4a8ac3a36810ba0021e4", "department": "Costume & Make-Up", "gender": 0, "id": 1330570, "job": "Costume Supervisor", "name": "Carolyn M. Fenton"}, {"credit_id": "539c4ab6c3a36810da0021f0", "department": "Costume & Make-Up", "gender": 0, "id": 1330574, "job": "Costume Supervisor", "name": "Beth Koenigsberg"}, {"credit_id": "54491ab70e0a267480001ba2", "department": "Art", "gender": 0, "id": 1336191, "job": "Set Designer", "name": "Sam Page"}, {"credit_id": "544919d9c3a3680fc30018bd", "department": "Art", "gender": 0, "id": 1339441, "job": "Set Designer", "name": "Tex Kadonaga"}, {"credit_id": "54491cf50e0a267483001b0c", "department": "Editing", "gender": 0, "id": 1352422, "job": "Dialogue Editor", "name": "Kim Foscato"}, {"credit_id": "544919f40e0a26748c001b09", "department": "Art", "gender": 0, "id": 1352962, "job": "Set Designer", "name": "Tammy S. Lee"}, {"credit_id": "5495a115c3a3680ff5002d71", "department": "Crew", "gender": 0, "id": 1357070, "job": "Transportation Coordinator", "name": "Denny Caira"}, {"credit_id": "5495a12f92514130fc002e94", "department": "Crew", "gender": 0, "id": 1357071, "job": "Transportation Coordinator", "name": "James Waitkus"}, {"credit_id": "5495976fc3a36811530026b0", "department": "Sound", "gender": 0, "id": 1360103, "job": "Supervising Sound Editor", "name": "Addison Teague"}, {"credit_id": "54491837c3a3680fb1001c5a", "department": "Art", "gender": 2, "id": 1376887, "job": "Set Designer", "name": "C. Scott Baker"}, {"credit_id": "54491878c3a3680fb4001c9d", "department": "Art", "gender": 0, "id": 1376888, "job": "Set Designer", "name": "Luke Caska"}, {"credit_id": "544918dac3a3680fa5001ae0", "department": "Art", "gender": 0, "id": 1376889, "job": "Set Designer", "name": "David Chow"}, {"credit_id": "544919110e0a267486001b68", "department": "Art", "gender": 0, "id": 1376890, "job": "Set Designer", "name": "Jonathan Dyer"}, {"credit_id": "54491967c3a3680faa001b5e", "department": "Art", "gender": 0, "id": 1376891, "job": "Set Designer", "name": "Joseph Hiura"}, {"credit_id": "54491997c3a3680fb1001c8a", "department": "Art", "gender": 0, "id": 1376892, "job": "Art Department Coordinator", "name": "Rebecca Jellie"}, {"credit_id": "544919ba0e0a26748f001b42", "department": "Art", "gender": 0, "id": 1376893, "job": "Set Designer", "name": "Robert Andrew Johnson"}, {"credit_id": "54491b1dc3a3680faa001b8c", "department": "Art", "gender": 0, "id": 1376895, "job": "Assistant Art Director", "name": "Mike Stassi"}, {"credit_id": "54491b79c3a3680fbb001826", "department": "Art", "gender": 0, "id": 1376897, "job": "Construction Coordinator", "name": "John Villarino"}, {"credit_id": "54491baec3a3680fb4001ce6", "department": "Art", "gender": 2, "id": 1376898, "job": "Assistant Art Director", "name": "Jeffrey Wisniewski"}, {"credit_id": "54491d2fc3a3680fb4001d07", "department": "Editing", "gender": 0, "id": 1376899, "job": "Dialogue Editor", "name": "Cheryl Nardi"}, {"credit_id": "54491d86c3a3680fa5001b2f", "department": "Editing", "gender": 0, "id": 1376901, "job": "Dialogue Editor", "name": "Marshall Winn"}, {"credit_id": "54491d9dc3a3680faa001bb0", "department": "Sound", "gender": 0, "id": 1376902, "job": "Supervising Sound Editor", "name": "Gwendolyn Yates Whittle"}, {"credit_id": "54491dc10e0a267486001bce", "department": "Sound", "gender": 0, "id": 1376903, "job": "Sound Re-Recording Mixer", "name": "William Stein"}, {"credit_id": "54491f500e0a26747c001c07", "department": "Crew", "gender": 0, "id": 1376909, "job": "Choreographer", "name": "Lula Washington"}, {"credit_id": "549599239251412c4e002a2e", "department": "Visual Effects", "gender": 0, "id": 1391692, "job": "Visual Effects Producer", "name": "Chris Del Conte"}, {"credit_id": "54959d54c3a36831b8001d9a", "department": "Visual Effects", "gender": 2, "id": 1391695, "job": "Visual Effects Supervisor", "name": "R. Christopher White"}, {"credit_id": "54959bdf9251412c4e002a66", "department": "Visual Effects", "gender": 0, "id": 1394070, "job": "Visual Effects Supervisor", "name": "Dan Lemmon"}, {"credit_id": "5495971d92514132ed002922", "department": "Sound", "gender": 0, "id": 1394129, "job": "Sound Effects Editor", "name": "Tim Nielsen"}, {"credit_id": "5592b25792514152cc0011aa", "department": "Crew", "gender": 0, "id": 1394286, "job": "CG Supervisor", "name": "Michael Mulholland"}, {"credit_id": "54959a329251416e2b004355", "department": "Crew", "gender": 0, "id": 1394750, "job": "Visual Effects Editor", "name": "Thomas Nittmann"}, {"credit_id": "54959d6dc3a3686ae9004401", "department": "Visual Effects", "gender": 0, "id": 1394755, "job": "Visual Effects Supervisor", "name": "Edson Williams"}, {"credit_id": "5495a08fc3a3686ae300441c", "department": "Editing", "gender": 0, "id": 1394953, "job": "Digital Intermediate", "name": "Christine Carr"}, {"credit_id": "55402d659251413d6d000249", "department": "Visual Effects", "gender": 0, "id": 1395269, "job": "Visual Effects Supervisor", "name": "John Bruno"}, {"credit_id": "54959e7b9251416e1e003f3e", "department": "Camera", "gender": 0, "id": 1398970, "job": "Steadicam Operator", "name": "David Emmerichs"}, {"credit_id": "54959734c3a3686ae10045e0", "department": "Sound", "gender": 0, "id": 1400906, "job": "Sound Effects Editor", "name": "Christopher Scarabosio"}, {"credit_id": "549595dd92514130fc002d79", "department": "Production", "gender": 0, "id": 1401784, "job": "Production Supervisor", "name": "Jennifer Teves"}, {"credit_id": "549596009251413af70028cc", "department": "Production", "gender": 0, "id": 1401785, "job": "Production Manager", "name": "Brigitte Yorke"}, {"credit_id": "549596e892514130fc002d99", "department": "Sound", "gender": 0, "id": 1401786, "job": "Sound Effects Editor", "name": "Ken Fischer"}, {"credit_id": "549598229251412c4e002a1c", "department": "Crew", "gender": 0, "id": 1401787, "job": "Special Effects Coordinator", "name": "Iain Hutton"}, {"credit_id": "549598349251416e2b00432b", "department": "Crew", "gender": 0, "id": 1401788, "job": "Special Effects Coordinator", "name": "Steve Ingram"}, {"credit_id": "54959905c3a3686ae3004324", "department": "Visual Effects", "gender": 0, "id": 1401789, "job": "Visual Effects Producer", "name": "Joyce Cox"}, {"credit_id": "5495994b92514132ed002951", "department": "Visual Effects", "gender": 0, "id": 1401790, "job": "Visual Effects Producer", "name": "Jenny Foster"}, {"credit_id": "549599cbc3a3686ae1004613", "department": "Crew", "gender": 0, "id": 1401791, "job": "Visual Effects Editor", "name": "Christopher Marino"}, {"credit_id": "549599f2c3a3686ae100461e", "department": "Crew", "gender": 0, "id": 1401792, "job": "Visual Effects Editor", "name": "Jim Milton"}, {"credit_id": "54959a51c3a3686af3003eb5", "department": "Visual Effects", "gender": 0, "id": 1401793, "job": "Visual Effects Producer", "name": "Cyndi Ochs"}, {"credit_id": "54959a7cc3a36811530026f4", "department": "Crew", "gender": 0, "id": 1401794, "job": "Visual Effects Editor", "name": "Lucas Putnam"}, {"credit_id": "54959b91c3a3680ff5002cb4", "department": "Visual Effects", "gender": 0, "id": 1401795, "job": "Visual Effects Supervisor", "name": "Anthony \'Max\' Ivins"}, {"credit_id": "54959bb69251412c4e002a5f", "department": "Visual Effects", "gender": 0, "id": 1401796, "job": "Visual Effects Supervisor", "name": "John Knoll"}, {"credit_id": "54959cbbc3a3686ae3004391", "department": "Visual Effects", "gender": 2, "id": 1401799, "job": "Visual Effects Supervisor", "name": "Eric Saindon"}, {"credit_id": "54959d06c3a3686ae90043f6", "department": "Visual Effects", "gender": 0, "id": 1401800, "job": "Visual Effects Supervisor", "name": "Wayne Stables"}, {"credit_id": "54959d259251416e1e003f11", "department": "Visual Effects", "gender": 0, "id": 1401801, "job": "Visual Effects Supervisor", "name": "David Stinnett"}, {"credit_id": "54959db49251413af7002975", "department": "Visual Effects", "gender": 0, "id": 1401803, "job": "Visual Effects Supervisor", "name": "Guy Williams"}, {"credit_id": "54959de4c3a3681153002750", "department": "Crew", "gender": 0, "id": 1401804, "job": "Stunt Coordinator", "name": "Stuart Thorp"}, {"credit_id": "54959ef2c3a3680fc60027f2", "department": "Lighting", "gender": 0, "id": 1401805, "job": "Best Boy Electric", "name": "Giles Coburn"}, {"credit_id": "54959f07c3a3680fc60027f9", "department": "Camera", "gender": 2, "id": 1401806, "job": "Still Photographer", "name": "Mark Fellman"}, {"credit_id": "54959f47c3a3681153002774", "department": "Lighting", "gender": 0, "id": 1401807, "job": "Lighting Technician", "name": "Scott Sprague"}, {"credit_id": "54959f8cc3a36831b8001df2", "department": "Visual Effects", "gender": 0, "id": 1401808, "job": "Animation Director", "name": "Jeremy Hollobon"}, {"credit_id": "54959fa0c3a36831b8001dfb", "department": "Visual Effects", "gender": 0, "id": 1401809, "job": "Animation Director", "name": "Orlando Meunier"}, {"credit_id": "54959fb6c3a3686af3003f54", "department": "Visual Effects", "gender": 0, "id": 1401810, "job": "Animation Director", "name": "Taisuke Tanimura"}, {"credit_id": "54959fd2c3a36831b8001e02", "department": "Costume & Make-Up", "gender": 0, "id": 1401812, "job": "Set Costumer", "name": "Lilia Mishel Acevedo"}, {"credit_id": "54959ff9c3a3686ae300440c", "department": "Costume & Make-Up", "gender": 0, "id": 1401814, "job": "Set Costumer", "name": "Alejandro M. Hernandez"}, {"credit_id": "5495a0ddc3a3686ae10046fe", "department": "Editing", "gender": 0, "id": 1401815, "job": "Digital Intermediate", "name": "Marvin Hall"}, {"credit_id": "5495a1f7c3a3686ae3004443", "department": "Production", "gender": 0, "id": 1401816, "job": "Publicist", "name": "Judy Alley"}, {"credit_id": "5592b29fc3a36869d100002f", "department": "Crew", "gender": 0, "id": 1418381, "job": "CG Supervisor", "name": "Mike Perry"}, {"credit_id": "5592b23a9251415df8001081", "department": "Crew", "gender": 0, "id": 1426854, "job": "CG Supervisor", "name": "Andrew Morley"}, {"credit_id": "55491e1192514104c40002d8", "department": "Art", "gender": 0, "id": 1438901, "job": "Conceptual Design", "name": "Seth Engstrom"}, {"credit_id": "5525d5809251417276002b06", "department": "Crew", "gender": 0, "id": 1447362, "job": "Visual Effects Art Director", "name": "Eric Oliver"}, {"credit_id": "554427ca925141586500312a", "department": "Visual Effects", "gender": 0, "id": 1447503, "job": "Modeling", "name": "Matsune Suzuki"}, {"credit_id": "551906889251415aab001c88", "department": "Art", "gender": 0, "id": 1447524, "job": "Art Department Manager", "name": "Paul Tobin"}, {"credit_id": "5592af8492514152cc0010de", "department": 

In [27]:
# we want only director name from the crew
def fetch_director(list):
  l=[]
  for i in ast.literal_eval(list):
    if i['job'] == 'Director':
      value = i['name']
      l.append(value)
      break
  return l

In [28]:
movies['crew'] = movies['crew'].apply(fetch_director)

In [29]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[Adventure, Fantasy, Action]","[ocean, drug abuse, exotic island, east india ...","[Johnny Depp, Orlando Bloom, Keira Knightley]",[Gore Verbinski]
2,206647,Spectre,A cryptic message from Bondâ€™s past sends him o...,"[Action, Adventure, Crime]","[spy, based on novel, secret agent, sequel, mi...","[Daniel Craig, Christoph Waltz, LÃ©a Seydoux]",[Sam Mendes]
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[Action, Crime, Drama, Thriller]","[dc comics, crime fighter, terrorist, secret i...","[Christian Bale, Michael Caine, Gary Oldman]",[Christopher Nolan]
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[Action, Adventure, Science Fiction]","[based on novel, mars, medallion, space travel...","[Taylor Kitsch, Lynn Collins, Samantha Morton]",[Andrew Stanton]

In [30]:
# Now we convert overview into list from string
movies['overview'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization.'

In [31]:
movies['overview'] = movies['overview'].apply(lambda y:y.split(" "))

In [32]:
movies.head(1)

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, Science Fiction]","[culture clash, future, space war, space colon...","[Sam Worthington, Zoe Saldana, Sigourney Weaver]",[James Cameron]

In [33]:
# We want here to form one word for each entity so that we got unique tags
# To iterate over each element of the list we will use list comprehension
movies['genres'] = movies['genres'].apply(lambda x: [y.replace(" ","") for y in x])
movies['keywords'] = movies['keywords'].apply(lambda x: [y.replace(" ","") for y in x])
movies['cast'] = movies['cast'].apply(lambda x: [y.replace(" ","") for y in x])
movies['crew'] = movies['crew'].apply(lambda x: [y.replace(" ","") for y in x])

In [34]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron]
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski]
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes]
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan]
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton]

In [35]:
# concatenation of all features into one
movies['tags'] = movies['overview']+movies['genres']+movies['keywords']+movies['cast']+movies['crew']

In [36]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin...","[Action, Adventure, Fantasy, ScienceFiction]","[cultureclash, future, spacewar, spacecolony, ...","[SamWorthington, ZoeSaldana, SigourneyWeaver]",[JamesCameron],"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d...","[Adventure, Fantasy, Action]","[ocean, drugabuse, exoticisland, eastindiatrad...","[JohnnyDepp, OrlandoBloom, KeiraKnightley]",[GoreVerbinski],"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send...","[Action, Adventure, Crime]","[spy, basedonnovel, secretagent, sequel, mi6, ...","[DanielCraig, ChristophWaltz, LÃ©aSeydoux]",[SamMendes],"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney...","[Action, Crime, Drama, Thriller]","[dccomics, crimefighter, terrorist, secretiden...","[ChristianBale, MichaelCaine, GaryOldman]",[ChristopherNolan],"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili...","[Action, Adventure, ScienceFiction]","[basedonnovel, mars, medallion, spacetravel, p...","[TaylorKitsch, LynnCollins, SamanthaMorton]",[AndrewStanton],"[John, Carter, is, a, war-weary,, former, mili..."

In [37]:
#creating new dataset for our problem
new_df = movies[['movie_id','title','tags']]

In [38]:
new_df

,movie_id,title,tags
0,19995,Avatar,"[In, the, 22nd, century,, a, paraplegic, Marin..."
1,285,Pirates of the Caribbean: At World's End,"[Captain, Barbossa,, long, believed, to, be, d..."
2,206647,Spectre,"[A, cryptic, message, from, Bondâ€™s, past, send..."
3,49026,The Dark Knight Rises,"[Following, the, death, of, District, Attorney..."
4,49529,John Carter,"[John, Carter, is, a, war-weary,, former, mili..."
...,...,...,...
4804,9367,El Mariachi,"[El, Mariachi, just, wants, to, play, his, gui..."
4805,72766,Newlyweds,"[A, newlywed, couple's, honeymoon, is, upended..."
4806,231617,"Signed, Sealed, Delivered","[""Signed,, Sealed,, Delivered"", introduces, a,..."
4807,126186,Shanghai Calling,"[When, ambitious, New, York, attorney, Sam, is..."
4808,25975,My Date with Drew,"[Ever, since, the, second, grade, when, he, fi..."

In [39]:
#converting list into para
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

<ipython-input-39-72662b1717fb>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

In [40]:
new_df['tags'][0]

'In the 22nd century, a paraplegic Marine is dispatched to the moon Pandora on a unique mission, but becomes torn between following orders and protecting an alien civilization. Action Adventure Fantasy ScienceFiction cultureclash future spacewar spacecolony society spacetravel futuristic romance space alien tribe alienplanet cgi marine soldier battle loveaffair antiwar powerrelations mindandsoul 3d SamWorthington ZoeSaldana SigourneyWeaver JamesCameron'

In [41]:
new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())

<ipython-input-41-574ea7a8c2f8>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(lambda x : x.lower())

In [42]:
new_df.head()
#Now our dataset is ready

,movie_id,title,tags
0,19995,Avatar,"in the 22nd century, a paraplegic marine is di..."
1,285,Pirates of the Caribbean: At World's End,"captain barbossa, long believed to be dead, ha..."
2,206647,Spectre,a cryptic message from bondâ€™s past sends him o...
3,49026,The Dark Knight Rises,following the death of district attorney harve...
4,49529,John Carter,"john carter is a war-weary, former military ca..."

**Text Vectorization**

In [43]:
#Now we will convert tags into vectors using Bag of words technique
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 5000,stop_words = 'english')

In [44]:
vectors = cv.fit_transform(new_df['tags']).toarray()

In [45]:
vectors

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [46]:
cv.get_feature_names()

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)

['000',
 '007',
 '10',
 '100',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '18th',
 '19',
 '1930s',
 '1940s',
 '1950',
 '1950s',
 '1960s',
 '1970s',
 '1980',
 '1980s',
 '1985',
 '1990s',
 '1999',
 '19th',
 '19thcentury',
 '20',
 '200',
 '2009',
 '20th',
 '24',
 '25',
 '30',
 '300',
 '3d',
 '40',
 '50',
 '500',
 '60',
 '60s',
 '70',
 '70s',
 'aaron',
 'aaroneckhart',
 'abandoned',
 'abducted',
 'abigailbreslin',
 'abilities',
 'ability',
 'able',
 'aboard',
 'abuse',
 'abusive',
 'academy',
 'accept',
 'accepted',
 'accepts',
 'access',
 'accident',
 'accidental',
 'accidentally',
 'accompanied',
 'accomplish',
 'account',
 'accountant',
 'accused',
 'ace',
 'achieve',
 'act',
 'acting',
 'action',
 'actionhero',
 'actions',
 'activist',
 'activities',
 'activity',
 'actor',
 'actors',
 'actress',
 'acts',
 'actual',
 'actually',
 'adam',
 'adams',
 'adamsandler',
 'adamshankman',
 'adaptation',
 'adapted',
 'addict',
 'addicted',
 'addiction',
 'adolescence',
 'adolescent',
 'adopt',
 'adopted',
 'adoption',
 'adopts',
 'adrienbrody',
 'adult',
 'adultanimation',
 'adultery',
 'adulthood',
 'adults',
 'advantage',
 'adventure',
 'adventures',
 'advertising',
 'advice',
 'affair',
 'affairs',
 'affection',
 'affections',
 'afghanistan',
 'africa',
 'african',
 'africanamerican',
 'aftercreditsstinger',
 'afterlife',
 'aftermath',
 'age',
 'aged',
 'agedifference',
 'agency',
 'agenda',
 'agent',
 'agents',
 'aggressive',
 'aging',
 'ago',
 'agree',
 'agrees',
 'ahead',
 'aid',
 'aided',
 'aids',
 'ailing',
 'air',
 'airplane',
 'airplanecrash',
 'airport',
 'aka',
 'al',
 'alabama',
 'alan',
 'alaska',
 'albert',
 'alcohol',
 'alcoholic',
 'alcoholism',
 'alecbaldwin',
 'alex',
 'alfredhitchcock',
 'ali',
 'alice',
 'alien',
 'alieninvasion',
 'alienlife',
 'aliens',
 'alike',
 'alive',
 'allen',
 'alliance',
 'allied',
 'allies',
 'allow',
 'allowing',
 'allows',
 'ally',
 'alongside',
 'alpacino',
 'alpha',
 'alter',
 'alternate',
 'alternative',
 'alzheimer',
 'amanda',
 'amandapeet',
 'amandaseyfried',
 'amateur',
 'amazing',
 'ambassador',
 'ambition',
 'ambitious',
 'ambulance',
 'ambush',
 'america',
 'american',
 'americanabroad',
 'americanfootball',
 'americans',
 'amid',
 'amidst',
 'amnesia',
 'amp',
 'amsterdam',
 'amusementpark',
 'amy',
 'amyadams',
 'amysmart',
 'ana',
 'anakin',
 'analyst',
 'anarchiccomedy',
 'ancient',
 'ancientrome',
 'ancientworld',
 'anderson',
 'andiemacdowell',
 'andrew',
 'android',
 'andy',
 'andygarcÃ­a',
 'angel',
 'angelabassett',
 'angeles',
 'angelinajolie',
 'angels',
 'anger',
 'anglee',
 'angry',
 'animal',
 'animalattack',
 'animalhorror',
 'animals',
 'animated',
 'animation',
 'anna',
 'annafaris',
 'anne',
 'annehathaway',
 'annemoss',
 'annettebening',
 'annie',
 'anniversary',
 'annual',
 'answer',
 'answers',
 'ant',
 'anthology',
 'anthony',
 'anthonyanderson',
 'anthonyhopkins',
 'anthropomorphism',
 'anti',
 'antics',
 'antihero',
 'antoinefuqua',
 'antoniobanderas',
 'antonyelchin',
 'apart',
 'apartheid',
 'apartment',
 'ape',
 'apes',
 'apocalypse',
 'apocalyptic',
 'apparent',
 'apparently',
 'appear',
 'appears',
 'apple',
 'appointed',
 'apprentice',
 'approach',
 'approaches',
 'approaching',
 'april',
 'aquarium',
 'arab',
 'arch',
 'archaeologist',
 'architect',
 'arctic',
 'area',
 'aren',
 'arena',
 'argument',
 'arise',
 'aristocrat',
 'armed',
 'arms',
 'army',
 'arnold',
 'arnoldschwarzenegger',
 'arrangedmarriage',
 'arrest',
 'arrested',
 'arrival',
 'arrive',
 'arrives',
 'arriving',
 'arrogant',
 'art',
 'arthur',
 'artificialintelligence',
 'artist',
 'artistic',
 'artists',
 'arts',
 'ashley',
 'ashleyjudd',
 'ashtonkutcher',
 'asia',
 'asian',
 'aside',
 'ask',
 'asked',
 'asking',
 'asks',
 'aspirations',
 'aspiring',
 'assassin',
 'assassinate',
 'assassination',
 'assassins',
 'assault',
 'assigned',
 'assignment',
 'assistant',
 'assumes',
 'asteroid',
 'astronaut',
 'astronauts',
 'asylum',
 'athlete',
 'atomicbomb',
 'attack',
 'attacked',
 'attacks',
 'attempt',
 'attempting',
 'attempts',
 'attending',
 'attends',
 'attention',
 'attitude',
 'attorney',
 'attracted',
 'attraction',
 'attractive',
 'audience',
 'audiences',
 'audition',
 'august',
 'aunt',
 'austin',
 'australia',
 'australian',
 'author',
 'authorities',
 'authority',
 'autism',
 'auto',
 'automobileracing',
 'avenge',
 'average',
 'avoid',
 'awaits',
 'awakens',
 'award',
 'away',
 'awry',
 'ax',
 'babe',
 'baby',
 'bachelor',
 'backdrop',
 'backed',
 'background',
 'backgrounds',
 'bad',
 'badly',
 'bag',
 'bahamas',
 'bail',
 'balance',
 'ball',
 'ballet',
 'baltimore',
 'band',
 'bandits',
 'bangkok',
 'banished',
 'bank',
 'banker',
 'bankrobber',
 'bankrobbery',
 'bar',
 'barely',
 'bargained',
 'barn',
 'barney',
 'barry',
 'barrylevinson',
 'bars',
 'base',
 'baseball',
 'based',
 'basedoncomicbook',
 'basedongraphicnovel',
 'basedonnovel',
 'basedonplay',
 'basedonstagemusical',
 'basedontrueevents',
 'basedontruestory',
 'basedontvseries',
 'basedonvideogame',
 'basedonyoungadultnovel',
 'basement',
 'basketball',
 'batman',
 'battle',
 'battlefield',
 'battles',
 'battling',
 'bay',
 'beach',
 'bear',
 'bears',
 'beast',
 'beasts',
 'beat',
 'beating',
 'beautiful',
 'beautifulwoman',
 'beauty',
 'becky',
 'becominganadult',
 'bed',
 'bedroom',
 'beer',
 'befriends',
 'began',
 'begin',
 'beginning',
 'begins',
 'behavior',
 'beings',
 'beliefs',
 'believe',
 'believed',
 'believes',
 'believing',
 'beloved',
 'ben',
 'benaffleck',
 'beneath',
 'benfoster',
 'beniciodeltoro',
 'benjamin',
 'benjaminbratt',
 'benkingsley',
 'bennett',
 'benstiller',
 'bent',
 'berlin',
 'best',
 'bestfriend',
 'bestfriendsinlove',
 'bet',
 'beth',
 'betrayal',
 'betrayed',
 'bettemidler',
 'better',
 'betty',
 'beverly',
 'bible',
 'big',
 'bigger',
 'biggest',
 'biker',
 'bikini',
 'billhader',
 'billionaire',
 'billmurray',
 'billnighy',
 'billpaxton',
 'billpullman',
 'billy',
 'billybobthornton',
 'billycrudup',
 'billycrystal',
 'biography',
 'bird',
 'birth',
 'birthday',
 'bisexual',
 'bishop',
 'bit',
 'bite',
 'bitter',
 'bizarre',
 'black',
 'blackmagic',
 'blackmail',
 'blackpeople',
 'blacksmith',
 'blade',
 'blame',
 'blind',
 'bliss',
 'block',
 'blonde',
 'blood',
 'bloodsplatter',
 'bloodthirsty',
 'bloody',
 'blow',
 'blue',
 'board',
 'boarding',
 'boardingschool',
 'boat',
 'bob',
 'bobby',
 'bobbyfarrelly',
 'bobhoskins',
 'bodies',
 'body',
 'bodyguard',
 'bold',
 'bollywood',
 'bomb',
 'bombing',
 'bond',
 'bonds',
 'bone',
 'book',
 'books',
 'border',
 'bored',
 'boredom',
 'boring',
 'born',
 'boss',
 'boston',
 'botched',
 'bound',
 'boundaries',
 'bounty',
 'bountyhunter',
 'bourne',
 'box',
 'boxer',
 'boxing',
 'boy',
 'boyfriend',
 'boys',
 'bradleycooper',
 'bradpitt',
 'brain',
 'brand',
 'brave',
 'bravery',
 'brazil',
 'brazilian',
 'break',
 'breakdown',
 'breaking',
 'breaks',
 'brendanfraser',
 'brendangleeson',
 'brent',
 'brettratner',
 'brian',
 'briandepalma',
 'bride',
 'bridesmaid',
 'bridge',
 'brief',
 'brielarson',
 'brien',
 'bright',
 'brilliant',
 'bring',
 'bringing',
 'brings',
 'brink',
 'britain',
 'british',
 'britishsecretservice',
 'brittanymurphy',
 'broadway',
 'broke',
 'broken',
 'broker',
 'bronx',
 'brooklyn',
 'brooks',
 'broom',
 'brothel',
 'brother',
 'brotherbrotherrelationship',
 'brothers',
 'brothersisterrelationship',
 'brought',
 'brown',
 'bruce',
 'brucegreenwood',
 'brucewillis',
 'brutal',
 'brutality',
 'brutally',
 'bryansinger',
 'buck',
 'buddies',
 'buddy',
 'buddycomedy',
 'budget',
 'build',
 'building',
 'built',
 'bully',
 'bullying',
 'bumbling',
 'bunny',
 'burglar',
 'buried',
 'bus',
 'bush',
 'business',
 'businessman',
 'bust',
 'busy',
 'butcher',
 'butler',
 'buy',
 'cabin',
 'caesar',
 'cage',
 'cairo',
 'cal',
 'california',
 'called',
 'calls',
 'calvin',
 'camcorder',
 'came',
 'camera',
 'cameraman',
 'cameras',
 'camerondiaz',
 'camp',
 'campaign',
 'campbell',
 'camping',
 'campus',
 'canada',
 'canadian',
 'cancer',
 'candidate',
 'candy',
 'cannibal',
 'capable',
 'capital',
 'capitalism',
 'capt',
 'captain',
 'captive',
 'capture',
 'captured',
 'captures',
 'car',
 'caraccident',
 'carchase',
 'carcrash',
 'card',
 'care',
 'career',
 'carefree',
 'caretaker',
 'caribbean',
 'carjourney',
 'carl',
 'carlagugino',
 'carmen',
 'carol',
 'carolina',
 'carrace',
 'carrie',
 'carry',
 'carrying',
 'cars',
 'cartel',
 'carter',
 'cartoon',
 'caryelwes',
 'case',
 'caseyaffleck',
 'cash',
 'casino',
 'cast',
 'castle',
 'cat',
 'cataclysm',
 'catastrophe',
 'catch',
 'catches',
 'cateblanchett',
 'catherinedeneuve',
 'catherinekeener',
 'catherinezeta',
 'catholic',
 'catholicism',
 'cattle',
 'caught',
 'cause',
 'caused',
 'causes',
 'causing',
 'cavalry',
 'cave',
 'cavemen',
 'celebrate',
 'celebrated',
 'celebration',
 'celebrity',
 'cellphone',
 'cemetery',
 'center',
 'centered',
 'centers',
 'central',
 'centuries',
 'century',
 'ceremony',
 'certain',
 'chain',
 'chainsaw',
 'challenge',
 'challenged',
 'challenges',
 'champion',
 'championship',
 'chance',
 'change',
 'changed',
 'changes',
 'changing',
 'channingtatum',
 'chaos',
 'chaotic',
 'chapter',
 'character',
 'characters',
 'charge',
 'charged',
 'charismatic',
 'charles',
 'charlie',
 'charliesheen',
 'charlizetheron',
 'charlotte',
 'charm',
 'charming',
 'chase',
 'chased',
 'chases',
 'chauffeur',
 'chazzpalminteri',
 'cheating',
 'cheerleader',
 'chef',
 'chemical',
 'cher',
 'chicago',
 'chicken',
 'chief',
 'child',
 'childabuse',
 'childhero',
 'childhood',
 'children',
 'chilling',
 'china',
 'chinese',
 'chip',
 'chiwetelejiofor',
 'chloÃ«gracemoretz',
 'chloÃ«sevigny',
 'chocolate',
 'choice',
 'choices',
 'choose',
 'chosen',
 'chowyun',
 'chris',
 'chriscolumbus',
 'chriscooper',
 'chrisevans',
 'chrishemsworth',
 'chrisklein',
 'chrispine',
 'chrisrock',
 'christ',
 'christian',
 'christianbale',
 'christianity',
 'christianslater',
 'christinaapplegate',
 'christinaricci',
 'christine',
 'christmas',
 'christmasparty',
 'christopher',
 'christopherlloyd',
 'christophernolan',
 'christopherplummer',
 'christopherwalken',
 'christophwaltz',
 'chrisweitz',
 'chronicle',
 'chronicles',
 'chuck',
 'church',
 'cia',
 'cigarettesmoking',
 'cillianmurphy',
 'cindy',
 'cinema',
 'circle',
 'circuit',
 'circumstances',
 'circus',
 'cities',
 'citizens',
 'city',
 'civil',
 'civilian',
 'civilization',
 'civilwar',
 'claim',
 'claims',
 'claire',
 'clairedanes',
 'clan',
 'clark',
 'clash',
 'class',
 'classes',
 'classic',
 'classmate',
 'classmates',
 'classroom',
 'claudevandamme',
 'clay',
 'clean',
 'clear',
 'clerk',
 'client',
 'clients',
 'climate',
 'climbing',
 'clinteastwood',
 'clique',
 'cliveowen',
 'clock',
 'clone',
 'cloning',
 'close',
 'closed',
 'closer',
 'club',
 'clubs',
 'clues',
 'clutches',
 'coach',
 'coast',
 'cocaine',
 'code',
 'cody',
 'coffin',
 'cohen',
 'col',
 'cold',
 'coldwar',
 'cole',
 'colin',
 'colinfarrell',
 'colinfirth',
 'collapse',
 'colleague',
 'colleagues',
 'collect',
 'collection',
 'collector',
 'college',
 'collide',
 'collision',
 'colonel',
 'colony',
 'color',
 'colorado',
 'colorful',
 'coma',
 'combat',
 'combined',
 'come',
 'comeback',
 'comedian',
 'comedic',
 'comedy',
 'comes',
 'comet',
 'comfort',
 'comic',
 'comics',
 'coming',
 'comingofage',
 'comingout',
 'command',
 'commander',
 'commercial',
 'commit',
 'commitment',
 'committed',
 'common',
 'communication',
 'community',
 'companion',
 'company',
 'compete',
 'competing',
 'competition',
 'complete',
 'completely',
 'complex',
 'complicated',
 'complications',
 'composer',
 'computer',
 'computervirus',
 'conan',
 'concert',
 'conclusion',
 'condition',
 'confederate',
 'confession',
 'confidence',
 'confident',
 'conflict',
 'confront',
 'confronted',
 'confronts',
 'confused',
 'congress',
 'conman',
 'connected',
 'connection',
 'connell',
 'connor',
 'conquer',
 'conscience',
 'consequences',
 'conservative',
 'considered',
 'conspiracy',
 'conspire',
 'constant',
 'constantly',
 'construction',
 'consumed',
 'contact',
 'contain',
 'contemporary',
 'contend',
 'contest',
 'continue',
 'continues',
 'continuing',
 'contract',
 'control',
 'controlled',
 'controlling',
 'controversial',
 'convention',
 'converge',
 'convict',
 'convicted',
 'convince',
 'convinced',
 'convinces',
 'cook',
 'cooking',
 'cool',
 'cooper',
 'cop',
 'cope',
 'cops',
 'core',
 'corner',
 'corners',
 'corporate',
 'corporation',
 'corpse',
 'corrupt',
 'corruption',
 'cost',
 ...]

In [47]:
# Now we will apply stemming to reduce the complexity
import nltk 
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [48]:
def stem(text):
  y=[]
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

In [49]:
new_df['tags'] = new_df['tags'].apply(stem)

<ipython-input-49-be18a4346d89>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['tags'] = new_df['tags'].apply(stem)

In [50]:
from sklearn.metrics.pairwise import cosine_similarity
similarity = cosine_similarity(vectors)
#cosine similarity will tell us similarity of each movie w.r to other movie

In [51]:
cosine_similarity(vectors).shape

(4806, 4806)

In [52]:
#This will sort all movie similar to the given movie in an numpy array(we took top 5 from that)
sorted(list(enumerate(similarity[0])),reverse = True,key=lambda x:x[1])[1:6]

[(539, 0.26089696604360174),
 (1194, 0.2581988897471611),
 (507, 0.25302403842552984),
 (260, 0.25110592822973776),
 (1216, 0.24944382578492943)]

In [53]:
def recommend(movie):
  movie_index = new_df[new_df['title'] == movie].index[0]   #will provide index of given movie
  distances = similarity[movie_index]                       #finding movie vector
  movies_list = sorted(list(enumerate(similarity[movie_index])),reverse = True,key=lambda x:x[1])[1:6]  #selecting top 5 movie

  for i in movies_list:
    print(new_df.iloc[i[0]].title)

In [54]:
recommend('Avatar')

Titan A.E.
Small Soldiers
Independence Day
Ender's Game
Aliens vs Predator: Requiem

In [55]:
import pickle
pickle.dump(new_df['title'].to_dict(),open('movies.pkl','wb'))

In [56]:
new_df['title'].to_dict()

{0: 'Avatar',
 1: "Pirates of the Caribbean: At World's End",
 2: 'Spectre',
 3: 'The Dark Knight Rises',
 4: 'John Carter',
 5: 'Spider-Man 3',
 6: 'Tangled',
 7: 'Avengers: Age of Ultron',
 8: 'Harry Potter and the Half-Blood Prince',
 9: 'Batman v Superman: Dawn of Justice',
 10: 'Superman Returns',
 11: 'Quantum of Solace',
 12: "Pirates of the Caribbean: Dead Man's Chest",
 13: 'The Lone Ranger',
 14: 'Man of Steel',
 15: 'The Chronicles of Narnia: Prince Caspian',
 16: 'The Avengers',
 17: 'Pirates of the Caribbean: On Stranger Tides',
 18: 'Men in Black 3',
 19: 'The Hobbit: The Battle of the Five Armies',
 20: 'The Amazing Spider-Man',
 21: 'Robin Hood',
 22: 'The Hobbit: The Desolation of Smaug',
 23: 'The Golden Compass',
 24: 'King Kong',
 25: 'Titanic',
 26: 'Captain America: Civil War',
 27: 'Battleship',
 28: 'Jurassic World',
 29: 'Skyfall',
 30: 'Spider-Man 2',
 31: 'Iron Man 3',
 32: 'Alice in Wonderland',
 33: 'X-Men: The Last Stand',
 34: 'Monsters University',
 35: 'Transformers: Revenge of the Fallen',
 36: 'Transformers: Age of Extinction',
 37: 'Oz: The Great and Powerful',
 38: 'The Amazing Spider-Man 2',
 39: 'TRON: Legacy',
 40: 'Cars 2',
 41: 'Green Lantern',
 42: 'Toy Story 3',
 43: 'Terminator Salvation',
 44: 'Furious 7',
 45: 'World War Z',
 46: 'X-Men: Days of Future Past',
 47: 'Star Trek Into Darkness',
 48: 'Jack the Giant Slayer',
 49: 'The Great Gatsby',
 50: 'Prince of Persia: The Sands of Time',
 51: 'Pacific Rim',
 52: 'Transformers: Dark of the Moon',
 53: 'Indiana Jones and the Kingdom of the Crystal Skull',
 54: 'The Good Dinosaur',
 55: 'Brave',
 56: 'Star Trek Beyond',
 57: 'WALLÂ·E',
 58: 'Rush Hour 3',
 59: '2012',
 60: 'A Christmas Carol',
 61: 'Jupiter Ascending',
 62: 'The Legend of Tarzan',
 63: 'The Chronicles of Narnia: The Lion, the Witch and the Wardrobe',
 64: 'X-Men: Apocalypse',
 65: 'The Dark Knight',
 66: 'Up',
 67: 'Monsters vs Aliens',
 68: 'Iron Man',
 69: 'Hugo',
 70: 'Wild Wild West',
 71: 'The Mummy: Tomb of the Dragon Emperor',
 72: 'Suicide Squad',
 73: 'Evan Almighty',
 74: 'Edge of Tomorrow',
 75: 'Waterworld',
 76: 'G.I. Joe: The Rise of Cobra',
 77: 'Inside Out',
 78: 'The Jungle Book',
 79: 'Iron Man 2',
 80: 'Snow White and the Huntsman',
 81: 'Maleficent',
 82: 'Dawn of the Planet of the Apes',
 83: 'The Lovers',
 84: '47 Ronin',
 85: 'Captain America: The Winter Soldier',
 86: 'Shrek Forever After',
 87: 'Tomorrowland',
 88: 'Big Hero 6',
 89: 'Wreck-It Ralph',
 90: 'The Polar Express',
 91: 'Independence Day: Resurgence',
 92: 'How to Train Your Dragon',
 93: 'Terminator 3: Rise of the Machines',
 94: 'Guardians of the Galaxy',
 95: 'Interstellar',
 96: 'Inception',
 97: 'Shin Godzilla',
 98: 'The Hobbit: An Unexpected Journey',
 99: 'The Fast and the Furious',
 100: 'The Curious Case of Benjamin Button',
 101: 'X-Men: First Class',
 102: 'The Hunger Games: Mockingjay - Part 2',
 103: "The Sorcerer's Apprentice",
 104: 'Poseidon',
 105: 'Alice Through the Looking Glass',
 106: 'Shrek the Third',
 107: 'Warcraft',
 108: 'Terminator Genisys',
 109: 'The Chronicles of Narnia: The Voyage of the Dawn Treader',
 110: 'Pearl Harbor',
 111: 'Transformers',
 112: 'Alexander',
 113: 'Harry Potter and the Order of the Phoenix',
 114: 'Harry Potter and the Goblet of Fire',
 115: 'Hancock',
 116: 'I Am Legend',
 117: 'Charlie and the Chocolate Factory',
 118: 'Ratatouille',
 119: 'Batman Begins',
 120: 'Madagascar: Escape 2 Africa',
 121: 'Night at the Museum: Battle of the Smithsonian',
 122: 'X-Men Origins: Wolverine',
 123: 'The Matrix Revolutions',
 124: 'Frozen',
 125: 'The Matrix Reloaded',
 126: 'Thor: The Dark World',
 127: 'Mad Max: Fury Road',
 128: 'Angels & Demons',
 129: 'Thor',
 130: 'Bolt',
 131: 'G-Force',
 132: 'Wrath of the Titans',
 133: 'Dark Shadows',
 134: 'Mission: Impossible - Rogue Nation',
 135: 'The Wolfman',
 136: 'Bee Movie',
 137: 'Kung Fu Panda 2',
 138: 'The Last Airbender',
 139: 'Mission: Impossible III',
 140: 'White House Down',
 141: 'Mars Needs Moms',
 142: 'Flushed Away',
 143: 'Pan',
 144: 'Mr. Peabody & Sherman',
 145: 'Troy',
 146: "Madagascar 3: Europe's Most Wanted",
 147: 'Die Another Day',
 148: 'Ghostbusters',
 149: 'Armageddon',
 150: 'Men in Black II',
 151: 'Beowulf',
 152: 'Kung Fu Panda 3',
 153: 'Mission: Impossible - Ghost Protocol',
 154: 'Rise of the Guardians',
 155: 'Fun with Dick and Jane',
 156: 'The Last Samurai',
 157: 'Exodus: Gods and Kings',
 158: 'Star Trek',
 159: 'Spider-Man',
 160: 'How to Train Your Dragon 2',
 161: 'Gods of Egypt',
 162: 'Stealth',
 163: 'Watchmen',
 164: 'Lethal Weapon 4',
 165: 'Hulk',
 166: 'G.I. Joe: Retaliation',
 167: 'Sahara',
 168: 'Final Fantasy: The Spirits Within',
 169: 'Captain America: The First Avenger',
 170: 'The World Is Not Enough',
 171: 'Master and Commander: The Far Side of the World',
 172: 'The Twilight Saga: Breaking Dawn - Part 2',
 173: 'Happy Feet Two',
 174: 'The Incredible Hulk',
 175: 'The BFG',
 176: 'The Revenant',
 177: 'Turbo',
 178: 'Rango',
 179: 'Penguins of Madagascar',
 180: 'The Bourne Ultimatum',
 181: 'Kung Fu Panda',
 182: 'Ant-Man',
 183: 'The Hunger Games: Catching Fire',
 184: 'Home',
 185: 'War of the Worlds',
 186: 'Bad Boys II',
 187: 'Puss in Boots',
 188: 'Salt',
 189: 'Noah',
 190: 'The Adventures of Tintin',
 191: 'Harry Potter and the Prisoner of Azkaban',
 192: 'Australia',
 193: 'After Earth',
 194: 'Dinosaur',
 195: 'Night at the Museum: Secret of the Tomb',
 196: 'Megamind',
 197: "Harry Potter and the Philosopher's Stone",
 198: 'R.I.P.D.',
 199: 'Pirates of the Caribbean: The Curse of the Black Pearl',
 200: 'The Hunger Games: Mockingjay - Part 1',
 201: 'The Da Vinci Code',
 202: 'Rio 2',
 203: 'X2',
 204: 'Fast Five',
 205: 'Sherlock Holmes: A Game of Shadows',
 206: 'Clash of the Titans',
 207: 'Total Recall',
 208: 'The 13th Warrior',
 209: 'The Bourne Legacy',
 210: 'Batman & Robin',
 211: 'How the Grinch Stole Christmas',
 212: 'The Day After Tomorrow',
 213: 'Mission: Impossible II',
 214: 'The Perfect Storm',
 215: 'Fantastic 4: Rise of the Silver Surfer',
 216: 'Life of Pi',
 217: 'Ghost Rider',
 218: 'Jason Bourne',
 219: "Charlie's Angels: Full Throttle",
 220: 'Prometheus',
 221: 'Stuart Little 2',
 222: 'Elysium',
 223: 'The Chronicles of Riddick',
 224: 'RoboCop',
 225: 'Speed Racer',
 226: 'How Do You Know',
 227: 'Knight and Day',
 228: 'Oblivion',
 229: 'Star Wars: Episode III - Revenge of the Sith',
 230: 'Star Wars: Episode II - Attack of the Clones',
 231: 'Monsters, Inc.',
 232: 'The Wolverine',
 233: 'Star Wars: Episode I - The Phantom Menace',
 234: 'The Croods',
 235: 'Asterix at the Olympic Games',
 236: 'Windtalkers',
 237: "The Huntsman: Winter's War",
 238: 'Teenage Mutant Ninja Turtles',
 239: 'Gravity',
 240: "Dante's Peak",
 241: 'Teenage Mutant Ninja Turtles: Out of the Shadows',
 242: 'Fantastic Four',
 243: 'Night at the Museum',
 244: 'San Andreas',
 245: 'Tomorrow Never Dies',
 246: 'The Patriot',
 247: "Ocean's Twelve",
 248: 'Mr. & Mrs. Smith',
 249: 'Insurgent',
 250: 'The Aviator',
 251: "Gulliver's Travels",
 252: 'The Green Hornet',
 253: '300: Rise of an Empire',
 254: 'The Smurfs',
 255: 'Home on the Range',
 256: 'Allegiant',
 257: 'Real Steel',
 258: 'The Smurfs 2',
 259: 'Speed 2: Cruise Control',
 260: "Ender's Game",
 261: 'Live Free or Die Hard',
 262: 'The Lord of the Rings: The Fellowship of the Ring',
 263: 'Around the World in 80 Days',
 264: 'Ali',
 265: 'The Cat in the Hat',
 266: 'I, Robot',
 267: 'Kingdom of Heaven',
 268: 'Stuart Little',
 269: 'The Princess and the Frog',
 270: 'The Martian',
 271: 'The Island',
 272: 'Town & Country',
 273: 'Gone in Sixty Seconds',
 274: 'Gladiator',
 275: 'Minority Report',
 276: 'Harry Potter and the Chamber of Secrets',
 277: 'Casino Royale',
 278: 'Planet of the Apes',
 279: 'Terminator 2: Judgment Day',
 280: 'Public Enemies',
 281: 'American Gangster',
 282: 'True Lies',
 283: 'The Taking of Pelham 1 2 3',
 284: 'Little Fockers',
 285: 'The Other Guys',
 286: 'Eraser',
 287: 'Django Unchained',
 288: 'The Hunchback of Notre Dame',
 289: "The Emperor's New Groove",
 290: 'The Expendables 2',
 291: 'National Treasure',
 292: 'Eragon',
 293: 'Where the Wild Things Are',
 294: 'Epic',
 295: 'The Tourist',
 296: 'End of Days',
 297: 'Blood Diamond',
 298: 'The Wolf of Wall Street',
 299: 'Batman Forever',
 300: 'Starship Troopers',
 301: 'Cloud Atlas',
 302: "Legend of the Guardians: The Owls of Ga'Hoole",
 303: 'Catwoman',
 304: 'Hercules',
 305: 'Treasure Planet',
 306: 'Land of the Lost',
 307: 'The Expendables 3',
 308: 'Point Break',
 309: 'Son of the Mask',
 310: 'In the Heart of the Sea',
 311: 'The Adventures of Pluto Nash',
 312: 'Green Zone',
 313: 'The Peanuts Movie',
 314: 'The Spanish Prisoner',
 315: 'The Mummy Returns',
 316: 'Gangs of New York',
 317: 'The Flowers of War',
 318: "Surf's Up",
 319: 'The Stepford Wives',
 320: 'Black Hawk Down',
 321: 'The Campaign',
 322: 'The Fifth Element',
 323: 'Sex and the City 2',
 324: 'The Road to El Dorado',
 325: 'Ice Age: Continental Drift',
 326: 'Cinderella',
 327: 'The Lovely Bones',
 328: 'Finding Nemo',
 329: 'The Lord of the Rings: The Return of the King',
 330: 'The Lord of the Rings: The Two Towers',
 331: 'Seventh Son',
 332: 'Lara Croft: Tomb Raider',
 333: 'Transcendence',
 334: 'Jurassic Park III',
 335: 'Rise of the Planet of the Apes',
 336: 'The Spiderwick Chronicles',
 337: 'A Good Day to Die Hard',
 338: 'The Alamo',
 339: 'The Incredibles',
 340: 'Cutthroat Island',
 341: 'Percy Jackson & the Olympians: The Lightning Thief',
 342: 'Men in Black',
 343: 'Toy Story 2',
 344: 'Unstoppable',
 345: 'Rush Hour 2',
 346: 'What Lies Beneath',
 347: 'Cloudy with a Chance of Meatballs',
 348: 'Ice Age: Dawn of the Dinosaurs',
 349: 'The Secret Life of Walter Mitty',
 350: "Charlie's Angels",
 351: 'The Departed',
 352: 'Mulan',
 353: 'Tropic Thunder',
 354: 'The Girl with the Dragon Tattoo',
 355: 'Die Hard: With a Vengeance',
 356: 'Sherlock Holmes',
 357: 'Ben-Hur',
 358: 'Atlantis: The Lost Empire',
 359: 'Alvin and the Chipmunks: The Road Chip',
 360: 'Valkyrie',
 361: "You Don't Mess with the Zohan",
 362: 'Pixels',
 363: 'A.I. Artificial Intelligence',
 364: 'The Haunted Mansion',
 365: 'Contact',
 366: 'Hollow Man',
 367: 'The Interpreter',
 368: 'Percy Jackson: Sea of Monsters',
 369: 'Lara Croft Tomb Raider: The Cradle of Life',
 370: 'Now You See Me 2',
 371: 'The Saint',
 372: 'Spy Game',
 373: 'Mission to Mars',
 374: 'Rio',
 375: 'Bicentennial Man',
 376: 'Volcano',
 377: "The Devil's Own",
 378: 'K-19: The Widowmaker',
 379: 'Conan the Barbarian',
 380: 'Cinderella Man',
 381: 'The Nutcracker: The Untold Story',
 382: 'Seabiscuit',
 383: 'Twister',
 384: 'Cast Away',
 385: 'Happy Feet',
 386: 'The Bourne Supremacy',
 387: 'Air Force One',
 388: "Ocean's Eleven",
 389: 'The Three Musketeers',
 390: 'Hotel Transylvania',
 391: 'Enchanted',
 392: 'Safe House',
 393: '102 Dalmatians',
 394: 'Tower Heist',
 395: 'The Holiday',
 396: 'Enemy of the State',
 397: "It's Complicated",
 398: "Ocean's Thirteen",
 399: 'Open Season',
 400: 'Divergent',
 401: 'Enemy at the Gates',
 402: 'The Rundown',
 403: 'Last Action Hero',
 404: 'Memoirs of a Geisha',
 405: 'The Fast and the Furious: Tokyo Drift',
 406: 'Arthur Christmas',
 407: 'Meet Joe Black',
 408: 'Collateral Damage',
 409: 'All That Jazz',
 410: 'Mirror Mirror',
 411: 'Scott Pilgrim vs. the World',
 412: 'The Core',
 413: 'Nutty Professor II: The Klumps',
 414: 'Scooby-Doo',
 415: 'Dredd',
 416: 'Click',
 417: 'Creepshow',
 418: 'Cats & Dogs 2 : The Revenge of Kitty Galore',
 419: 'Jumper',
 420: 'Hellboy II: The Golden Army',
 421: 'Zodiac',
 422: 'The 6th Day',
 423: 'Bruce Almighty',
 424: 'The Expendables',
 425: 'Mission: Impossible',
 426: 'The Hunger Games',
 427: 'The Hangover Part II',
 428: 'Batman Returns',
 429: 'Over the Hedge',
 430: 'Lilo & Stitch',
 431: "Charlotte's Web",
 432: 'Deep Impact',
 433: 'RED 2',
 434: 'The Longest Yard',
 435: 'Alvin and the Chipmunks: Chipwrecked',
 436: 'Grown Ups 2',
 437: 'Get Smart',
 438: "Something's Gotta Give",
 439: 'Shutter Island',
 440: 'Four Christmases',
 441: 'Robots',
 442: 'Face/Off',
 443: 'Bedtime Stories',
 444: 'Road to Perdition',
 445: 'Just Go with It',
 446: 'Con Air',
 447: 'Eagle Eye',
 448: 'Cold Mountain',
 449: 'The Book of Eli',
 450: 'Flubber',
 451: 'The Haunting',
 452: 'Space Jam',
 453: 'The Pink Panther',
 454: 'The Day the Earth Stood Still',
 455: 'Conspiracy Theory',
 456: 'Fury',
 457: 'Six Days Seven Nights',
 458: 'Yogi Bear',
 459: 'Spirit: Stallion of the Cimarron',
 460: 'Zookeeper',
 461: 'Lost in Space',
 462: 'The Manchurian Candidate',
 463: 'DÃ©jÃ  Vu',
 464: 'Hotel Transylvania 2',
 465: 'Fantasia 2000',
 466: 'The Time Machine',
 467: 'Mighty Joe Young',
 468: 'Swordfish',
 469: 'The Legend of Zorro',
 470: 'What Dreams May Come',
 471: 'Little Nicky',
 472: 'The Brothers Grimm',
 473: 'Mars Attacks!',
 474: 'Evolution',
 475: 'The Edge',
 476: 'Surrogates',
 477: 'Thirteen Days',
 478: 'Daylight',
 479: 'Walking With Dinosaurs',
 480: 'Battlefield Earth',
 481: 'Looney Tunes: Back in Action',
 482: 'Nine',
 483: 'Timeline',
 484: 'The Postman',
 485: 'Babe: Pig in the City',
 486: 'The Last Witch Hunter',
 487: 'Red Planet',
 488: 'Arthur and the Invisibles',
 489: 'Oceans',
 490: 'A Sound of Thunder',
 491: 'Pompeii',
 492: 'Top Cat Begins',
 493: 'A Beautiful Mind',
 494: 'The Lion King',
 495: 'Journey 2: The Mysterious Island',
 496: 'Cloudy with a Chance of Meatballs 2',
 497: 'Red Dragon',
 498: 'Hidalgo',
 499: 'Jack and Jill',
 500: '2 Fast 2 Furious',
 501: 'The Little Prince',
 502: 'The Invasion',
 503: 'The Adventures of Rocky & Bullwinkle',
 504: 'The Secret Life of Pets',
 505: 'The League of Extraordinary Gentlemen',
 506: 'Despicable Me 2',
 507: 'Independence Day',
 508: 'The Lost World: Jurassic Park',
 509: 'Madagascar',
 510: 'Children of Men',
 511: 'X-Men',
 512: 'Wanted',
 513: 'The Rock',
 514: 'Ice Age: The Meltdown',
 515: '50 First Dates',
 516: 'Hairspray',
 517: 'Exorcist: The Beginning',
 518: 'Inspector Gadget',
 519: 'Now You See Me',
 520: 'Grown Ups',
 521: 'The Terminal',
 522: 'Hotel for Dogs',
 523: 'Vertical Limit',
 524: "Charlie Wilson's War",
 525: 'Shark Tale',
 526: 'Dreamgirls',
 527: 'Be Cool',
 528: 'Munich',
 529: 'Tears of the Sun',
 530: 'Killers',
 531: 'The Man from U.N.C.L.E.',
 532: 'Spanglish',
 533: 'Monster House',
 534: 'Bandits',
 535: 'First Knight',
 536: 'Anna and the King',
 537: 'Immortals',
 538: 'Hostage',
 539: 'Titan A.E.',
 540: 'Hollywood Homicide',
 541: 'Soldier',
 542: 'Carriers',
 543: 'Monkeybone',
 544: 'Flight of the Phoenix',
 545: 'Unbreakable',
 546: 'Minions',
 547: 'Sucker Punch',
 548: 'Snake Eyes',
 549: 'Sphere',
 550: 'The Angry Birds Movie',
 551: "Fool's Gold",
 552: 'Funny People',
 553: 'The Kingdom',
 554: 'Talladega Nights: The Ballad of Ricky Bobby',
 555: 'Dr. Dolittle 2',
 556: 'Braveheart',
 557: 'Jarhead',
 558: 'The Simpsons Movie',
 559: 'The Majestic',
 560: 'Driven',
 561: 'Two Brothers',
 562: 'The Village',
 563: 'Doctor Dolittle',
 564: 'Signs',
 565: 'Shrek 2',
 566: 'Cars',
 567: 'Runaway Bride',
 568: 'xXx',
 569: 'The SpongeBob Movie: Sponge Out of Water',
 570: 'Ransom',
 571: 'Inglourious Basterds',
 572: 'Hook',
 573: 'Die Hard 2',
 574: 'S.W.A.T.',
 575: 'Vanilla Sky',
 576: 'Lady in the Water',
 577: 'AVP: Alien vs. Predator',
 578: 'Alvin and the Chipmunks: The Squeakquel',
 579: 'We Were Soldiers',
 580: 'Olympus Has Fallen',
 581: 'Star Trek: Insurrection',
 582: 'Battle: Los Angeles',
 583: 'Big Fish',
 584: 'Wolf',
 585: 'War Horse',
 586: 'The Monuments Men',
 587: 'The Abyss',
 588: 'Wall Street: Money Never Sleeps',
 589: 'Dracula Untold',
 590: 'The Siege',
 591: 'Stardust',
 592: 'Seven Years in Tibet',
 593: 'The Dilemma',
 594: 'Bad Company',
 595: 'Doom',
 596: 'I Spy',
 597: 'Underworld: Awakening',
 598: 'Rock of Ages',
 599: "Hart's War",
 600: 'Killer Elite',
 601: 'Rollerball',
 602: 'Ballistic: Ecks vs. Sever',
 603: 'Hard Rain',
 604: 'Osmosis Jones',
 605: "Legends of Oz: Dorothy's Return",
 606: 'Blackhat',
 607: 'Sky Captain and the World of Tomorrow',
 608: 'Basic Instinct 2',
 609: 'Escape Plan',
 610: 'The Legend of Hercules',
 611: 'The Sum of All Fears',
 612: 'The Twilight Saga: Eclipse',
 613: 'The Score',
 614: 'Despicable Me',
 615: 'Money Train',
 616: 'Ted 2',
 617: 'Agora',
 618: 'Mystery Men',
 619: 'Hall Pass',
 620: 'The Insider',
 621: 'The Finest Hours',
 622: 'Body of Lies',
 623: 'Dinner for Schmucks',
 624: 'Abraham Lincoln: Vampire Hunter',
 625: 'Entrapment',
 626: 'The X Files',
 627: 'The Last Legion',
 628: 'Saving Private Ryan',
 629: 'Need for Speed',
 630: 'What Women Want',
 631: 'Ice Age',
 632: 'Dreamcatcher',
 633: 'Lincoln',
 634: 'The Matrix',
 635: 'Apollo 13',
 636: 'The Santa Clause 2',
 637: 'Les MisÃ©rables',
 638: "You've Got Mail",
 639: 'Step Brothers',
 640: 'The Mask of Zorro',
 641: 'Due Date',
 642: 'Unbroken',
 643: 'Space Cowboys',
 644: 'Cliffhanger',
 645: 'Broken Arrow',
 646: 'The Kid',
 647: 'World Trade Center',
 648: 'Mona Lisa Smile',
 649: 'The Dictator',
 650: 'Eyes Wide Shut',
 651: 'Annie',
 652: 'Focus',
 653: 'This Means War',
 654: 'Blade: Trinity',
 655: 'Red Dawn',
 656: 'Primary Colors',
 657: 'Resident Evil: Retribution',
 658: 'Death Race',
 659: 'The Long Kiss Goodnight',
 660: 'Proof of Life',
 661: 'Zathura: A Space Adventure',
 662: 'Fight Club',
 663: 'We Are Marshall',
 664: 'Hudson Hawk',
 665: 'Lucky Numbers',
 666: 'I, Frankenstein',
 667: 'Oliver Twist',
 668: 'Elektra',
 669: 'Sin City: A Dame to Kill For',
 670: 'Random Hearts',
 671: 'Everest',
 672: 'Perfume: The Story of a Murderer',
 673: 'Austin Powers in Goldmember',
 674: 'Astro Boy',
 675: 'Jurassic Park',
 676: 'Wyatt Earp',
 677: 'Clear and Present Danger',
 678: 'Dragon Blade',
 679: 'Little Man',
 680: 'U-571',
 681: 'The American President',
 682: 'The Love Guru',
 683: '3000 Miles to Graceland',
 684: 'The Hateful Eight',
 685: 'Blades of Glory',
 686: 'Hop',
 687: '300',
 688: 'Meet the Fockers',
 689: 'Marley & Me',
 690: 'The Green Mile',
 691: 'Wild Hogs',
 692: 'Chicken Little',
 693: 'Gone Girl',
 694: 'The Bourne Identity',
 695: 'GoldenEye',
 696: "The General's Daughter",
 697: 'The Truman Show',
 698: 'The Prince of Egypt',
 699: 'Daddy Day Care',
 700: '2 Guns',
 701: 'Cats & Dogs',
 702: 'The Italian Job',
 703: 'Two Weeks Notice',
 704: 'Antz',
 705: 'Couples Retreat',
 706: 'Days of Thunder',
 707: 'Cheaper by the Dozen 2',
 708: 'Maze Runner: The Scorch Trials',
 709: 'Eat Pray Love',
 710: 'The Family Man',
 711: 'RED',
 712: 'Any Given Sunday',
 713: 'The Horse Whisperer',
 714: 'Collateral',
 715: 'The Scorpion King',
 716: 'Ladder 49',
 717: 'Jack Reacher',
 718: 'Deep Blue Sea',
 719: 'This Is It',
 720: 'Contagion',
 721: 'Kangaroo Jack',
 722: 'Coraline',
 723: 'The Happening',
 724: 'Man on Fire',
 725: 'The Shaggy Dog',
 726: 'Starsky & Hutch',
 727: 'Jingle All the Way',
 728: 'Hellboy',
 729: 'A Civil Action',
 730: 'ParaNorman',
 731: 'The Jackal',
 732: 'Paycheck',
 733: 'Up Close & Personal',
 734: 'The Tale of Despereaux',
 735: 'The Tuxedo',
 736: 'Under Siege 2: Dark Territory',
 737: 'Jack Ryan: Shadow Recruit',
 738: 'Joy',
 739: 'London Has Fallen',
 740: 'Alien: Resurrection',
 741: 'Shooter',
 742: 'The Boxtrolls',
 743: 'Practical Magic',
 744: 'The Lego Movie',
 745: 'Miss Congeniality 2: Armed and Fabulous',
 746: 'Reign of Fire',
 747: 'Gangster Squad',
 748: 'Year One',
 749: 'Invictus',
 750: 'State of Play',
 751: 'Duplicity',
 752: 'My Favorite Martian',
 753: 'The Sentinel',
 754: 'Planet 51',
 755: 'Star Trek: Nemesis',
 756: 'Intolerable Cruelty',
 757: 'Trouble with the Curve',
 758: 'Edge of Darkness',
 759: 'The Relic',
 760: 'Analyze That',
 761: 'Righteous Kill',
 762: 'Mercury Rising',
 763: 'The Soloist',
 764: 'The Legend of Bagger Vance',

In [57]:
pickle.dump(new_df,open('new_df.pkl','wb'))

In [58]:
pickle.dump(similarity,open('similarity.pkl','wb'))